Fix by Casian Pantea:   modified DSR.m to work with new cell/matrix syntax in Octave 3.6 Fix by Pete Donnell:   changed dsr from octave script to shell script   - auto-detects path to octave   - checks that the correct number of arguments were passed in

diff --git a/dsr b/dsr
--- a/dsr
+++ b/dsr
@@ -1,4 +1,13 @@
-#!/usr/bin/octave -qH
-#disp(argv(){1})
-warning("off");
-DSR(argv(){1});
+#!/bin/sh
+OCTAVE=$(which octave)
+if [ -z $OCTAVE ]
+then
+	echo "Error: octave binary not found"
+	exit 1
+fi
+if [ $# -ne 1 ]
+then
+	echo "Usage: dsr filename"
+	exit 2
+fi
+echo "warning('off');DSR('$1');" | $OCTAVE -qH --no-window-system
